### ISSUE TITLE
WebLint tool

### ISSUE THREAD

**Issue by tooomm** [travis-ci/travis-yml#100]
>We are working on a new yml parsing library, travis-yml, which is slowly being rolled out on the Travis CI hosted platform. We are also working on a new WebLint tool.

Copied from https://yaml.travis-ci.org/
What's the progress here as the page/tool is not available currently.

**Comment by svenfuchs** [comment]
@tooomm the status is that we are still working on this, it's a fairly big project.

however, you can already use http://config.travis-ci.org/. does that work for you?

**Comment by tooomm** [comment]
Thanks for the news and the other link. Will check it out.

Looking forward to future updates here.

**Comment by ferdnyc** [comment]
@svenfuchs That tool is a cool idea, but is there any way the page layout could responsively adjust to lay out _vertically_, instead of _horizontally_, if the canvas width is below a certain size? I feel like I'm spying on my code through the gaps in a picket fence:

![image](https://user-images.githubusercontent.com/538020/61346310-3ac93800-a826-11e9-81bd-a1742c3ae303.png)

(Sorry if this isn't the right place, please let me know if there's somewhere else I should file that request.)

**Comment by svenfuchs** [comment]
(the explorer has been moved to https://config.travis-ci.com/explore in the meantime, it might move around more in the future)

@ferdnyc thanks! the explorer is experimental and certainly needs a lot more work, that is right.

i'm going to close this issue here, please feel free to reopen if needed.
