### ISSUE TITLE
Update Documentation

### ISSUE THREAD

**Issue by carlad** [travis-ci/travis-yml#34]
- [ ] add new pages with `key` based link to docs
- [ ] remove references to `lint` web app
- [ ] add links to config.travis-ci.org (dependent on https://github.com/travis-pro/team-teal/issues/2569)

**Comment by plaindocs** [comment]
What I currently have is https://deploy-preview-1554--musing-lamport-7fb66c.netlify.com/user/travisyml/ from work in https://github.com/travis-ci/docs-travis-ci-com/pull/1554 .

As I see it there are main options:

* Make it so that docs.travis-ci.org/user/yamlref/<KEY> redirects straight to the link I have for each key.
* Add title and description on my side, expanding the current list, and you can just link to /yamlref/#<key> which will take you the relevant section on the page, with a link to more info

Thoughts welcome.

**Comment by carlad** [comment]
@backspace do you have any thoughts on plaindocs' comments above? Is there a preferred way in terms of what works best with `travis-web`?

**Comment by carlad** [comment]
sorry - just saw your comment on the accompany issue:
https://github.com/travis-ci/travis-yml/issues/33#issuecomment-367040167

> Regarding “link to documentation”, it would be ideal if the link were accomplished through anchors, or some consistent way we can generate a link from a key. We could instead maintain a map of key to URL, but that seems unwieldy.

**Comment by franklinyu** [comment]
On [WebLint](https://lint.travis-ci.org/) page:

> We are also working on a new WebLint tool.

So is there “a new WebLint tool”?

**Comment by carlad** [comment]
Hi @franklinyu there is one in the works. It's not quite production-ready, and is designed to work with the new `travis-yml` parsing library that's in very early pre-alpha release. If you'd like more info about opting in to using this new library and getting access to the new config parsing tool, please drop an email to support@travis-ci.com and they'll be able to help.

**Comment by svenfuchs** [comment]
i think this can be closed. all three items seem to be implemented.

please reopen if needed.
