### ISSUE TITLE
travis-lint vs travis-yaml vs travis-yml

### ISSUE THREAD

**Issue by quasilyte** [travis-ci/travis-yml#74]
The travis-lint says it's deprecated and replaced with travis-yaml.
The travis-yaml readme has no links to travis-yml (this repo), but this travis-yml readme says that it's a replacement for travis-yaml.

What's the story behind this? I'm so confused.

Also, the readme says nothing about linting the `.travis.yml` file.
There are no examples on how to use it as a drop-in replacement for `travis-lint`.

As far as I understand, travis-yaml is a library, so installing `gem install travis-yaml` doesn't give anything that replace `travis-lint` executable/script right away. I don't understand how to use it instead of `travis-lint`, honestly. :)

**Comment by NullVoxPopuli** [comment]
TravisCI team, can you help us lost folk? :)

**Comment by svenfuchs** [comment]
Sorry for the confusion, everyone.

Both `travis-lint` and `travis-yaml` are indeed deprecated. `travis-yml` is currently active as a dark release, we'll blog about this soon.

The CLI `lint` command still uses `travis-yaml` because our API still does. I'll see about addressing that asap.

If you are looking for a Web UI to validate your build configuration there is https://config.travis-ci.com/explore

I am going to close this issue here, please feel free to reopen if needed.
